### ISSUE TITLE
Virtual numbers no longer work?

### ISSUE THREAD

**Issue by Ladeforged** [LRTT/LINEREGISTER#2]
I tried virtual numbers last week n all okay, but now no pin send, any fix or what other service to use for numbers?

**Comment by LRTT** [comment]
Hi, we tested it with our numbers and it works perfectly fine.
1. Is it a problem with your virtual numbers?
2. Are you using the right phone numbers/country code?

**Comment by Ladeforged** [comment]
Do you know of a service that doesn't have virtual numbers?, Everything worked 2 weeks ago perfectly fine I made 100-150 without issues, I'm just stuck at the moment

**Comment by LRTT** [comment]
Sorry, but we don't have any.

**Comment by LRTT** [comment]
**CLOSED**: Still working.
