### ISSUE TITLE
How many tokens we can generate from 1 ip? I means what's the limit per ip

### ISSUE THREAD

**Issue by Gurlal1944** [LRTT/LINEREGISTER#3]

**Comment by LRTT** [comment]
About ≤4~5 accounts/ip, But you can bypass it by using proxy.

**Comment by Gurlal1944** [comment]
Can u post an example how to use proxy in ur script

**Comment by LRTT** [comment]
register.py:59
Tutorial: https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module
