### ISSUE TITLE
Human verification required.

### ISSUE THREAD

**Issue by LRTT** [LRTT/LINEREGISTER#4]
Update, Captcha required.

**Comment by sammy80s** [comment]
Why username account always "NO NAME" and when i trying running bot not sending respon?

**Comment by LRTT** [comment]
> Why username account always "NO NAME" and when i trying running bot not sending respon?

1. You can find it in the register.py/e2ee.py.
2. Maybe it's because your config file or your bot.

**Comment by sammy80s** [comment]
How about human verification?

**Comment by LRTT** [comment]
You can bypass human verification by using residential proxy for now.
We're trying to find a way to solve this problem ASAP.

**Comment by MuayThai69** [comment]
Doneeeeee

**Comment by LRTT** [comment]
Solved, Bypass captcha by using older version of line.

**Comment by dianawue** [comment]
vertipikasi manusia di butuhkan
solusinya menggunakan line versi lama
tapi masalahnya sekarang line versi lama tidak bisa di gunakan apakah ada solusi lain..?
