### ISSUE TITLE
Not getting pin code anymore on entered numbers

### ISSUE THREAD

**Issue by iAmGuru0** [LRTT/LINEREGISTER#7]

**Comment by IllusionZG** [comment]
maybe you need to resend pin if using temporary numbers.

**Comment by iAmGuru0** [comment]
So i just figured out that m facing this problem with only Indian numbers. I tried many sim card numbers from but its not sending otp. But when i tried numbers from a friend from another country its working fine so what exactly the problem is.

**Comment by IllusionZG** [comment]
@LRTT close the issue :+1:
